/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppValuationRouteImport } from './routes/_app.valuation'
import { Route as AppTiktokOauthCallbackRouteImport } from './routes/_app.tiktok-oauth-callback'
import { Route as AppTiktokDataRouteImport } from './routes/_app.tiktok-data'
import { Route as AppTiktokConnectRouteImport } from './routes/_app.tiktok-connect'
import { Route as AppStoreDataRouteImport } from './routes/_app.store-data'
import { Route as AppSnapchatOauthCallbackRouteImport } from './routes/_app.snapchat-oauth-callback'
import { Route as AppSnapchatDataRouteImport } from './routes/_app.snapchat-data'
import { Route as AppSnapchatConnectRouteImport } from './routes/_app.snapchat-connect'
import { Route as AppShopifyConnectRouteImport } from './routes/_app.shopify-connect'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRiskScannerRouteImport } from './routes/_app.risk-scanner'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlUploadRouteImport } from './routes/_app.pl-upload'
import { Route as AppPlDataRouteImport } from './routes/_app.pl-data'
import { Route as AppOptimizationRouteImport } from './routes/_app.optimization'
import { Route as AppMetaOauthCallbackRouteImport } from './routes/_app.meta-oauth-callback'
import { Route as AppMetaDataRouteImport } from './routes/_app.meta-data'
import { Route as AppMetaConnectRouteImport } from './routes/_app.meta-connect'
import { Route as AppInvestmentMemoRouteImport } from './routes/_app.investment-memo'
import { Route as AppGoogleOauthCallbackRouteImport } from './routes/_app.google-oauth-callback'
import { Route as AppGoogleDataRouteImport } from './routes/_app.google-data'
import { Route as AppGoogleConnectRouteImport } from './routes/_app.google-connect'
import { Route as AppGa4OauthCallbackRouteImport } from './routes/_app.ga4-oauth-callback'
import { Route as AppGa4DataRouteImport } from './routes/_app.ga4-data'
import { Route as AppGa4ConnectRouteImport } from './routes/_app.ga4-connect'
import { Route as AppFinancialNormalizerRouteImport } from './routes/_app.financial-normalizer'
import { Route as AppExitScoreRouteImport } from './routes/_app.exit-score'
import { Route as AppDataSourcesRouteImport } from './routes/_app.data-sources'
import { Route as AppDataRoomRouteImport } from './routes/_app.data-room'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBuyerMatchingRouteImport } from './routes/_app.buyer-matching'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppBankStatementsUploadRouteImport } from './routes/_app.bank-statements-upload'
import { Route as AppBankStatementsDataRouteImport } from './routes/_app.bank-statements-data'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminDocumentsRouteImport } from './routes/_app.admin.documents'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValuationRoute = AppValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AppRoute,
} as any)
const AppTiktokOauthCallbackRoute = AppTiktokOauthCallbackRouteImport.update({
  id: '/tiktok-oauth-callback',
  path: '/tiktok-oauth-callback',
  getParentRoute: () => AppRoute,
} as any)
const AppTiktokDataRoute = AppTiktokDataRouteImport.update({
  id: '/tiktok-data',
  path: '/tiktok-data',
  getParentRoute: () => AppRoute,
} as any)
const AppTiktokConnectRoute = AppTiktokConnectRouteImport.update({
  id: '/tiktok-connect',
  path: '/tiktok-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreDataRoute = AppStoreDataRouteImport.update({
  id: '/store-data',
  path: '/store-data',
  getParentRoute: () => AppRoute,
} as any)
const AppSnapchatOauthCallbackRoute =
  AppSnapchatOauthCallbackRouteImport.update({
    id: '/snapchat-oauth-callback',
    path: '/snapchat-oauth-callback',
    getParentRoute: () => AppRoute,
  } as any)
const AppSnapchatDataRoute = AppSnapchatDataRouteImport.update({
  id: '/snapchat-data',
  path: '/snapchat-data',
  getParentRoute: () => AppRoute,
} as any)
const AppSnapchatConnectRoute = AppSnapchatConnectRouteImport.update({
  id: '/snapchat-connect',
  path: '/snapchat-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppShopifyConnectRoute = AppShopifyConnectRouteImport.update({
  id: '/shopify-connect',
  path: '/shopify-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskScannerRoute = AppRiskScannerRouteImport.update({
  id: '/risk-scanner',
  path: '/risk-scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlUploadRoute = AppPlUploadRouteImport.update({
  id: '/pl-upload',
  path: '/pl-upload',
  getParentRoute: () => AppRoute,
} as any)
const AppPlDataRoute = AppPlDataRouteImport.update({
  id: '/pl-data',
  path: '/pl-data',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizationRoute = AppOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => AppRoute,
} as any)
const AppMetaOauthCallbackRoute = AppMetaOauthCallbackRouteImport.update({
  id: '/meta-oauth-callback',
  path: '/meta-oauth-callback',
  getParentRoute: () => AppRoute,
} as any)
const AppMetaDataRoute = AppMetaDataRouteImport.update({
  id: '/meta-data',
  path: '/meta-data',
  getParentRoute: () => AppRoute,
} as any)
const AppMetaConnectRoute = AppMetaConnectRouteImport.update({
  id: '/meta-connect',
  path: '/meta-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentMemoRoute = AppInvestmentMemoRouteImport.update({
  id: '/investment-memo',
  path: '/investment-memo',
  getParentRoute: () => AppRoute,
} as any)
const AppGoogleOauthCallbackRoute = AppGoogleOauthCallbackRouteImport.update({
  id: '/google-oauth-callback',
  path: '/google-oauth-callback',
  getParentRoute: () => AppRoute,
} as any)
const AppGoogleDataRoute = AppGoogleDataRouteImport.update({
  id: '/google-data',
  path: '/google-data',
  getParentRoute: () => AppRoute,
} as any)
const AppGoogleConnectRoute = AppGoogleConnectRouteImport.update({
  id: '/google-connect',
  path: '/google-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppGa4OauthCallbackRoute = AppGa4OauthCallbackRouteImport.update({
  id: '/ga4-oauth-callback',
  path: '/ga4-oauth-callback',
  getParentRoute: () => AppRoute,
} as any)
const AppGa4DataRoute = AppGa4DataRouteImport.update({
  id: '/ga4-data',
  path: '/ga4-data',
  getParentRoute: () => AppRoute,
} as any)
const AppGa4ConnectRoute = AppGa4ConnectRouteImport.update({
  id: '/ga4-connect',
  path: '/ga4-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialNormalizerRoute = AppFinancialNormalizerRouteImport.update({
  id: '/financial-normalizer',
  path: '/financial-normalizer',
  getParentRoute: () => AppRoute,
} as any)
const AppExitScoreRoute = AppExitScoreRouteImport.update({
  id: '/exit-score',
  path: '/exit-score',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSourcesRoute = AppDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoomRoute = AppDataRoomRouteImport.update({
  id: '/data-room',
  path: '/data-room',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerMatchingRoute = AppBuyerMatchingRouteImport.update({
  id: '/buyer-matching',
  path: '/buyer-matching',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBankStatementsUploadRoute = AppBankStatementsUploadRouteImport.update({
  id: '/bank-statements-upload',
  path: '/bank-statements-upload',
  getParentRoute: () => AppRoute,
} as any)
const AppBankStatementsDataRoute = AppBankStatementsDataRouteImport.update({
  id: '/bank-statements-data',
  path: '/bank-statements-data',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDocumentsRoute = AppAdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/bank-statements-data': typeof AppBankStatementsDataRoute
  '/bank-statements-upload': typeof AppBankStatementsUploadRoute
  '/billing': typeof AppBillingRoute
  '/buyer-matching': typeof AppBuyerMatchingRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-room': typeof AppDataRoomRoute
  '/data-sources': typeof AppDataSourcesRoute
  '/exit-score': typeof AppExitScoreRoute
  '/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/ga4-connect': typeof AppGa4ConnectRoute
  '/ga4-data': typeof AppGa4DataRoute
  '/ga4-oauth-callback': typeof AppGa4OauthCallbackRoute
  '/google-connect': typeof AppGoogleConnectRoute
  '/google-data': typeof AppGoogleDataRoute
  '/google-oauth-callback': typeof AppGoogleOauthCallbackRoute
  '/investment-memo': typeof AppInvestmentMemoRoute
  '/meta-connect': typeof AppMetaConnectRoute
  '/meta-data': typeof AppMetaDataRoute
  '/meta-oauth-callback': typeof AppMetaOauthCallbackRoute
  '/optimization': typeof AppOptimizationRoute
  '/pl-data': typeof AppPlDataRoute
  '/pl-upload': typeof AppPlUploadRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/risk-scanner': typeof AppRiskScannerRoute
  '/settings': typeof AppSettingsRoute
  '/shopify-connect': typeof AppShopifyConnectRoute
  '/snapchat-connect': typeof AppSnapchatConnectRoute
  '/snapchat-data': typeof AppSnapchatDataRoute
  '/snapchat-oauth-callback': typeof AppSnapchatOauthCallbackRoute
  '/store-data': typeof AppStoreDataRoute
  '/tiktok-connect': typeof AppTiktokConnectRoute
  '/tiktok-data': typeof AppTiktokDataRoute
  '/tiktok-oauth-callback': typeof AppTiktokOauthCallbackRoute
  '/valuation': typeof AppValuationRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/documents': typeof AppAdminDocumentsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/bank-statements-data': typeof AppBankStatementsDataRoute
  '/bank-statements-upload': typeof AppBankStatementsUploadRoute
  '/billing': typeof AppBillingRoute
  '/buyer-matching': typeof AppBuyerMatchingRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-room': typeof AppDataRoomRoute
  '/data-sources': typeof AppDataSourcesRoute
  '/exit-score': typeof AppExitScoreRoute
  '/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/ga4-connect': typeof AppGa4ConnectRoute
  '/ga4-data': typeof AppGa4DataRoute
  '/ga4-oauth-callback': typeof AppGa4OauthCallbackRoute
  '/google-connect': typeof AppGoogleConnectRoute
  '/google-data': typeof AppGoogleDataRoute
  '/google-oauth-callback': typeof AppGoogleOauthCallbackRoute
  '/investment-memo': typeof AppInvestmentMemoRoute
  '/meta-connect': typeof AppMetaConnectRoute
  '/meta-data': typeof AppMetaDataRoute
  '/meta-oauth-callback': typeof AppMetaOauthCallbackRoute
  '/optimization': typeof AppOptimizationRoute
  '/pl-data': typeof AppPlDataRoute
  '/pl-upload': typeof AppPlUploadRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/risk-scanner': typeof AppRiskScannerRoute
  '/settings': typeof AppSettingsRoute
  '/shopify-connect': typeof AppShopifyConnectRoute
  '/snapchat-connect': typeof AppSnapchatConnectRoute
  '/snapchat-data': typeof AppSnapchatDataRoute
  '/snapchat-oauth-callback': typeof AppSnapchatOauthCallbackRoute
  '/store-data': typeof AppStoreDataRoute
  '/tiktok-connect': typeof AppTiktokConnectRoute
  '/tiktok-data': typeof AppTiktokDataRoute
  '/tiktok-oauth-callback': typeof AppTiktokOauthCallbackRoute
  '/valuation': typeof AppValuationRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/documents': typeof AppAdminDocumentsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/bank-statements-data': typeof AppBankStatementsDataRoute
  '/_app/bank-statements-upload': typeof AppBankStatementsUploadRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/buyer-matching': typeof AppBuyerMatchingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/data-room': typeof AppDataRoomRoute
  '/_app/data-sources': typeof AppDataSourcesRoute
  '/_app/exit-score': typeof AppExitScoreRoute
  '/_app/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/_app/ga4-connect': typeof AppGa4ConnectRoute
  '/_app/ga4-data': typeof AppGa4DataRoute
  '/_app/ga4-oauth-callback': typeof AppGa4OauthCallbackRoute
  '/_app/google-connect': typeof AppGoogleConnectRoute
  '/_app/google-data': typeof AppGoogleDataRoute
  '/_app/google-oauth-callback': typeof AppGoogleOauthCallbackRoute
  '/_app/investment-memo': typeof AppInvestmentMemoRoute
  '/_app/meta-connect': typeof AppMetaConnectRoute
  '/_app/meta-data': typeof AppMetaDataRoute
  '/_app/meta-oauth-callback': typeof AppMetaOauthCallbackRoute
  '/_app/optimization': typeof AppOptimizationRoute
  '/_app/pl-data': typeof AppPlDataRoute
  '/_app/pl-upload': typeof AppPlUploadRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/risk-scanner': typeof AppRiskScannerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shopify-connect': typeof AppShopifyConnectRoute
  '/_app/snapchat-connect': typeof AppSnapchatConnectRoute
  '/_app/snapchat-data': typeof AppSnapchatDataRoute
  '/_app/snapchat-oauth-callback': typeof AppSnapchatOauthCallbackRoute
  '/_app/store-data': typeof AppStoreDataRoute
  '/_app/tiktok-connect': typeof AppTiktokConnectRoute
  '/_app/tiktok-data': typeof AppTiktokDataRoute
  '/_app/tiktok-oauth-callback': typeof AppTiktokOauthCallbackRoute
  '/_app/valuation': typeof AppValuationRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/documents': typeof AppAdminDocumentsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-callback'
    | '/data-deletion'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/bank-statements-data'
    | '/bank-statements-upload'
    | '/billing'
    | '/buyer-matching'
    | '/dashboard'
    | '/data-room'
    | '/data-sources'
    | '/exit-score'
    | '/financial-normalizer'
    | '/ga4-connect'
    | '/ga4-data'
    | '/ga4-oauth-callback'
    | '/google-connect'
    | '/google-data'
    | '/google-oauth-callback'
    | '/investment-memo'
    | '/meta-connect'
    | '/meta-data'
    | '/meta-oauth-callback'
    | '/optimization'
    | '/pl-data'
    | '/pl-upload'
    | '/profile'
    | '/reports'
    | '/risk-scanner'
    | '/settings'
    | '/shopify-connect'
    | '/snapchat-connect'
    | '/snapchat-data'
    | '/snapchat-oauth-callback'
    | '/store-data'
    | '/tiktok-connect'
    | '/tiktok-data'
    | '/tiktok-oauth-callback'
    | '/valuation'
    | '/admin/audit'
    | '/admin/documents'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-callback'
    | '/data-deletion'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/bank-statements-data'
    | '/bank-statements-upload'
    | '/billing'
    | '/buyer-matching'
    | '/dashboard'
    | '/data-room'
    | '/data-sources'
    | '/exit-score'
    | '/financial-normalizer'
    | '/ga4-connect'
    | '/ga4-data'
    | '/ga4-oauth-callback'
    | '/google-connect'
    | '/google-data'
    | '/google-oauth-callback'
    | '/investment-memo'
    | '/meta-connect'
    | '/meta-data'
    | '/meta-oauth-callback'
    | '/optimization'
    | '/pl-data'
    | '/pl-upload'
    | '/profile'
    | '/reports'
    | '/risk-scanner'
    | '/settings'
    | '/shopify-connect'
    | '/snapchat-connect'
    | '/snapchat-data'
    | '/snapchat-oauth-callback'
    | '/store-data'
    | '/tiktok-connect'
    | '/tiktok-data'
    | '/tiktok-oauth-callback'
    | '/valuation'
    | '/admin/audit'
    | '/admin/documents'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth-callback'
    | '/data-deletion'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_app/admin'
    | '/_app/bank-statements-data'
    | '/_app/bank-statements-upload'
    | '/_app/billing'
    | '/_app/buyer-matching'
    | '/_app/dashboard'
    | '/_app/data-room'
    | '/_app/data-sources'
    | '/_app/exit-score'
    | '/_app/financial-normalizer'
    | '/_app/ga4-connect'
    | '/_app/ga4-data'
    | '/_app/ga4-oauth-callback'
    | '/_app/google-connect'
    | '/_app/google-data'
    | '/_app/google-oauth-callback'
    | '/_app/investment-memo'
    | '/_app/meta-connect'
    | '/_app/meta-data'
    | '/_app/meta-oauth-callback'
    | '/_app/optimization'
    | '/_app/pl-data'
    | '/_app/pl-upload'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/risk-scanner'
    | '/_app/settings'
    | '/_app/shopify-connect'
    | '/_app/snapchat-connect'
    | '/_app/snapchat-data'
    | '/_app/snapchat-oauth-callback'
    | '/_app/store-data'
    | '/_app/tiktok-connect'
    | '/_app/tiktok-data'
    | '/_app/tiktok-oauth-callback'
    | '/_app/valuation'
    | '/_app/admin/audit'
    | '/_app/admin/documents'
    | '/_app/admin/users'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  DataDeletionRoute: typeof DataDeletionRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/valuation': {
      id: '/_app/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof AppValuationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tiktok-oauth-callback': {
      id: '/_app/tiktok-oauth-callback'
      path: '/tiktok-oauth-callback'
      fullPath: '/tiktok-oauth-callback'
      preLoaderRoute: typeof AppTiktokOauthCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tiktok-data': {
      id: '/_app/tiktok-data'
      path: '/tiktok-data'
      fullPath: '/tiktok-data'
      preLoaderRoute: typeof AppTiktokDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tiktok-connect': {
      id: '/_app/tiktok-connect'
      path: '/tiktok-connect'
      fullPath: '/tiktok-connect'
      preLoaderRoute: typeof AppTiktokConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store-data': {
      id: '/_app/store-data'
      path: '/store-data'
      fullPath: '/store-data'
      preLoaderRoute: typeof AppStoreDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snapchat-oauth-callback': {
      id: '/_app/snapchat-oauth-callback'
      path: '/snapchat-oauth-callback'
      fullPath: '/snapchat-oauth-callback'
      preLoaderRoute: typeof AppSnapchatOauthCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snapchat-data': {
      id: '/_app/snapchat-data'
      path: '/snapchat-data'
      fullPath: '/snapchat-data'
      preLoaderRoute: typeof AppSnapchatDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snapchat-connect': {
      id: '/_app/snapchat-connect'
      path: '/snapchat-connect'
      fullPath: '/snapchat-connect'
      preLoaderRoute: typeof AppSnapchatConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopify-connect': {
      id: '/_app/shopify-connect'
      path: '/shopify-connect'
      fullPath: '/shopify-connect'
      preLoaderRoute: typeof AppShopifyConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk-scanner': {
      id: '/_app/risk-scanner'
      path: '/risk-scanner'
      fullPath: '/risk-scanner'
      preLoaderRoute: typeof AppRiskScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pl-upload': {
      id: '/_app/pl-upload'
      path: '/pl-upload'
      fullPath: '/pl-upload'
      preLoaderRoute: typeof AppPlUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pl-data': {
      id: '/_app/pl-data'
      path: '/pl-data'
      fullPath: '/pl-data'
      preLoaderRoute: typeof AppPlDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/optimization': {
      id: '/_app/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof AppOptimizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meta-oauth-callback': {
      id: '/_app/meta-oauth-callback'
      path: '/meta-oauth-callback'
      fullPath: '/meta-oauth-callback'
      preLoaderRoute: typeof AppMetaOauthCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meta-data': {
      id: '/_app/meta-data'
      path: '/meta-data'
      fullPath: '/meta-data'
      preLoaderRoute: typeof AppMetaDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meta-connect': {
      id: '/_app/meta-connect'
      path: '/meta-connect'
      fullPath: '/meta-connect'
      preLoaderRoute: typeof AppMetaConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investment-memo': {
      id: '/_app/investment-memo'
      path: '/investment-memo'
      fullPath: '/investment-memo'
      preLoaderRoute: typeof AppInvestmentMemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/google-oauth-callback': {
      id: '/_app/google-oauth-callback'
      path: '/google-oauth-callback'
      fullPath: '/google-oauth-callback'
      preLoaderRoute: typeof AppGoogleOauthCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/google-data': {
      id: '/_app/google-data'
      path: '/google-data'
      fullPath: '/google-data'
      preLoaderRoute: typeof AppGoogleDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/google-connect': {
      id: '/_app/google-connect'
      path: '/google-connect'
      fullPath: '/google-connect'
      preLoaderRoute: typeof AppGoogleConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ga4-oauth-callback': {
      id: '/_app/ga4-oauth-callback'
      path: '/ga4-oauth-callback'
      fullPath: '/ga4-oauth-callback'
      preLoaderRoute: typeof AppGa4OauthCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ga4-data': {
      id: '/_app/ga4-data'
      path: '/ga4-data'
      fullPath: '/ga4-data'
      preLoaderRoute: typeof AppGa4DataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ga4-connect': {
      id: '/_app/ga4-connect'
      path: '/ga4-connect'
      fullPath: '/ga4-connect'
      preLoaderRoute: typeof AppGa4ConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financial-normalizer': {
      id: '/_app/financial-normalizer'
      path: '/financial-normalizer'
      fullPath: '/financial-normalizer'
      preLoaderRoute: typeof AppFinancialNormalizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exit-score': {
      id: '/_app/exit-score'
      path: '/exit-score'
      fullPath: '/exit-score'
      preLoaderRoute: typeof AppExitScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-sources': {
      id: '/_app/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof AppDataSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-room': {
      id: '/_app/data-room'
      path: '/data-room'
      fullPath: '/data-room'
      preLoaderRoute: typeof AppDataRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer-matching': {
      id: '/_app/buyer-matching'
      path: '/buyer-matching'
      fullPath: '/buyer-matching'
      preLoaderRoute: typeof AppBuyerMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank-statements-upload': {
      id: '/_app/bank-statements-upload'
      path: '/bank-statements-upload'
      fullPath: '/bank-statements-upload'
      preLoaderRoute: typeof AppBankStatementsUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank-statements-data': {
      id: '/_app/bank-statements-data'
      path: '/bank-statements-data'
      fullPath: '/bank-statements-data'
      preLoaderRoute: typeof AppBankStatementsDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/documents': {
      id: '/_app/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AppAdminDocumentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminDocumentsRoute: typeof AppAdminDocumentsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminDocumentsRoute: AppAdminDocumentsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBankStatementsDataRoute: typeof AppBankStatementsDataRoute
  AppBankStatementsUploadRoute: typeof AppBankStatementsUploadRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBuyerMatchingRoute: typeof AppBuyerMatchingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataRoomRoute: typeof AppDataRoomRoute
  AppDataSourcesRoute: typeof AppDataSourcesRoute
  AppExitScoreRoute: typeof AppExitScoreRoute
  AppFinancialNormalizerRoute: typeof AppFinancialNormalizerRoute
  AppGa4ConnectRoute: typeof AppGa4ConnectRoute
  AppGa4DataRoute: typeof AppGa4DataRoute
  AppGa4OauthCallbackRoute: typeof AppGa4OauthCallbackRoute
  AppGoogleConnectRoute: typeof AppGoogleConnectRoute
  AppGoogleDataRoute: typeof AppGoogleDataRoute
  AppGoogleOauthCallbackRoute: typeof AppGoogleOauthCallbackRoute
  AppInvestmentMemoRoute: typeof AppInvestmentMemoRoute
  AppMetaConnectRoute: typeof AppMetaConnectRoute
  AppMetaDataRoute: typeof AppMetaDataRoute
  AppMetaOauthCallbackRoute: typeof AppMetaOauthCallbackRoute
  AppOptimizationRoute: typeof AppOptimizationRoute
  AppPlDataRoute: typeof AppPlDataRoute
  AppPlUploadRoute: typeof AppPlUploadRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskScannerRoute: typeof AppRiskScannerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopifyConnectRoute: typeof AppShopifyConnectRoute
  AppSnapchatConnectRoute: typeof AppSnapchatConnectRoute
  AppSnapchatDataRoute: typeof AppSnapchatDataRoute
  AppSnapchatOauthCallbackRoute: typeof AppSnapchatOauthCallbackRoute
  AppStoreDataRoute: typeof AppStoreDataRoute
  AppTiktokConnectRoute: typeof AppTiktokConnectRoute
  AppTiktokDataRoute: typeof AppTiktokDataRoute
  AppTiktokOauthCallbackRoute: typeof AppTiktokOauthCallbackRoute
  AppValuationRoute: typeof AppValuationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBankStatementsDataRoute: AppBankStatementsDataRoute,
  AppBankStatementsUploadRoute: AppBankStatementsUploadRoute,
  AppBillingRoute: AppBillingRoute,
  AppBuyerMatchingRoute: AppBuyerMatchingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataRoomRoute: AppDataRoomRoute,
  AppDataSourcesRoute: AppDataSourcesRoute,
  AppExitScoreRoute: AppExitScoreRoute,
  AppFinancialNormalizerRoute: AppFinancialNormalizerRoute,
  AppGa4ConnectRoute: AppGa4ConnectRoute,
  AppGa4DataRoute: AppGa4DataRoute,
  AppGa4OauthCallbackRoute: AppGa4OauthCallbackRoute,
  AppGoogleConnectRoute: AppGoogleConnectRoute,
  AppGoogleDataRoute: AppGoogleDataRoute,
  AppGoogleOauthCallbackRoute: AppGoogleOauthCallbackRoute,
  AppInvestmentMemoRoute: AppInvestmentMemoRoute,
  AppMetaConnectRoute: AppMetaConnectRoute,
  AppMetaDataRoute: AppMetaDataRoute,
  AppMetaOauthCallbackRoute: AppMetaOauthCallbackRoute,
  AppOptimizationRoute: AppOptimizationRoute,
  AppPlDataRoute: AppPlDataRoute,
  AppPlUploadRoute: AppPlUploadRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskScannerRoute: AppRiskScannerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopifyConnectRoute: AppShopifyConnectRoute,
  AppSnapchatConnectRoute: AppSnapchatConnectRoute,
  AppSnapchatDataRoute: AppSnapchatDataRoute,
  AppSnapchatOauthCallbackRoute: AppSnapchatOauthCallbackRoute,
  AppStoreDataRoute: AppStoreDataRoute,
  AppTiktokConnectRoute: AppTiktokConnectRoute,
  AppTiktokDataRoute: AppTiktokDataRoute,
  AppTiktokOauthCallbackRoute: AppTiktokOauthCallbackRoute,
  AppValuationRoute: AppValuationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  DataDeletionRoute: DataDeletionRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
