/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppValuationRouteImport } from './routes/app.valuation'
import { Route as AppShopifyConnectRouteImport } from './routes/app.shopify-connect'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRiskScannerRouteImport } from './routes/app.risk-scanner'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOptimizationRouteImport } from './routes/app.optimization'
import { Route as AppInvestmentMemoRouteImport } from './routes/app.investment-memo'
import { Route as AppFinancialNormalizerRouteImport } from './routes/app.financial-normalizer'
import { Route as AppExitScoreRouteImport } from './routes/app.exit-score'
import { Route as AppDataSourcesRouteImport } from './routes/app.data-sources'
import { Route as AppDataRoomRouteImport } from './routes/app.data-room'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBuyerMatchingRouteImport } from './routes/app.buyer-matching'
import { Route as AppBillingRouteImport } from './routes/app.billing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValuationRoute = AppValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AppRoute,
} as any)
const AppShopifyConnectRoute = AppShopifyConnectRouteImport.update({
  id: '/shopify-connect',
  path: '/shopify-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskScannerRoute = AppRiskScannerRouteImport.update({
  id: '/risk-scanner',
  path: '/risk-scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizationRoute = AppOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentMemoRoute = AppInvestmentMemoRouteImport.update({
  id: '/investment-memo',
  path: '/investment-memo',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialNormalizerRoute = AppFinancialNormalizerRouteImport.update({
  id: '/financial-normalizer',
  path: '/financial-normalizer',
  getParentRoute: () => AppRoute,
} as any)
const AppExitScoreRoute = AppExitScoreRouteImport.update({
  id: '/exit-score',
  path: '/exit-score',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSourcesRoute = AppDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoomRoute = AppDataRoomRouteImport.update({
  id: '/data-room',
  path: '/data-room',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerMatchingRoute = AppBuyerMatchingRouteImport.update({
  id: '/buyer-matching',
  path: '/buyer-matching',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/buyer-matching': typeof AppBuyerMatchingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/exit-score': typeof AppExitScoreRoute
  '/app/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/app/investment-memo': typeof AppInvestmentMemoRoute
  '/app/optimization': typeof AppOptimizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk-scanner': typeof AppRiskScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shopify-connect': typeof AppShopifyConnectRoute
  '/app/valuation': typeof AppValuationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/buyer-matching': typeof AppBuyerMatchingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/exit-score': typeof AppExitScoreRoute
  '/app/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/app/investment-memo': typeof AppInvestmentMemoRoute
  '/app/optimization': typeof AppOptimizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk-scanner': typeof AppRiskScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shopify-connect': typeof AppShopifyConnectRoute
  '/app/valuation': typeof AppValuationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/buyer-matching': typeof AppBuyerMatchingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/exit-score': typeof AppExitScoreRoute
  '/app/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/app/investment-memo': typeof AppInvestmentMemoRoute
  '/app/optimization': typeof AppOptimizationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk-scanner': typeof AppRiskScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shopify-connect': typeof AppShopifyConnectRoute
  '/app/valuation': typeof AppValuationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/billing'
    | '/app/buyer-matching'
    | '/app/dashboard'
    | '/app/data-room'
    | '/app/data-sources'
    | '/app/exit-score'
    | '/app/financial-normalizer'
    | '/app/investment-memo'
    | '/app/optimization'
    | '/app/profile'
    | '/app/reports'
    | '/app/risk-scanner'
    | '/app/settings'
    | '/app/shopify-connect'
    | '/app/valuation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/billing'
    | '/app/buyer-matching'
    | '/app/dashboard'
    | '/app/data-room'
    | '/app/data-sources'
    | '/app/exit-score'
    | '/app/financial-normalizer'
    | '/app/investment-memo'
    | '/app/optimization'
    | '/app/profile'
    | '/app/reports'
    | '/app/risk-scanner'
    | '/app/settings'
    | '/app/shopify-connect'
    | '/app/valuation'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/billing'
    | '/app/buyer-matching'
    | '/app/dashboard'
    | '/app/data-room'
    | '/app/data-sources'
    | '/app/exit-score'
    | '/app/financial-normalizer'
    | '/app/investment-memo'
    | '/app/optimization'
    | '/app/profile'
    | '/app/reports'
    | '/app/risk-scanner'
    | '/app/settings'
    | '/app/shopify-connect'
    | '/app/valuation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/valuation': {
      id: '/app/valuation'
      path: '/valuation'
      fullPath: '/app/valuation'
      preLoaderRoute: typeof AppValuationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shopify-connect': {
      id: '/app/shopify-connect'
      path: '/shopify-connect'
      fullPath: '/app/shopify-connect'
      preLoaderRoute: typeof AppShopifyConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk-scanner': {
      id: '/app/risk-scanner'
      path: '/risk-scanner'
      fullPath: '/app/risk-scanner'
      preLoaderRoute: typeof AppRiskScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/optimization': {
      id: '/app/optimization'
      path: '/optimization'
      fullPath: '/app/optimization'
      preLoaderRoute: typeof AppOptimizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investment-memo': {
      id: '/app/investment-memo'
      path: '/investment-memo'
      fullPath: '/app/investment-memo'
      preLoaderRoute: typeof AppInvestmentMemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financial-normalizer': {
      id: '/app/financial-normalizer'
      path: '/financial-normalizer'
      fullPath: '/app/financial-normalizer'
      preLoaderRoute: typeof AppFinancialNormalizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exit-score': {
      id: '/app/exit-score'
      path: '/exit-score'
      fullPath: '/app/exit-score'
      preLoaderRoute: typeof AppExitScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-sources': {
      id: '/app/data-sources'
      path: '/data-sources'
      fullPath: '/app/data-sources'
      preLoaderRoute: typeof AppDataSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-room': {
      id: '/app/data-room'
      path: '/data-room'
      fullPath: '/app/data-room'
      preLoaderRoute: typeof AppDataRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer-matching': {
      id: '/app/buyer-matching'
      path: '/buyer-matching'
      fullPath: '/app/buyer-matching'
      preLoaderRoute: typeof AppBuyerMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppBuyerMatchingRoute: typeof AppBuyerMatchingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataRoomRoute: typeof AppDataRoomRoute
  AppDataSourcesRoute: typeof AppDataSourcesRoute
  AppExitScoreRoute: typeof AppExitScoreRoute
  AppFinancialNormalizerRoute: typeof AppFinancialNormalizerRoute
  AppInvestmentMemoRoute: typeof AppInvestmentMemoRoute
  AppOptimizationRoute: typeof AppOptimizationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskScannerRoute: typeof AppRiskScannerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopifyConnectRoute: typeof AppShopifyConnectRoute
  AppValuationRoute: typeof AppValuationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppBuyerMatchingRoute: AppBuyerMatchingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataRoomRoute: AppDataRoomRoute,
  AppDataSourcesRoute: AppDataSourcesRoute,
  AppExitScoreRoute: AppExitScoreRoute,
  AppFinancialNormalizerRoute: AppFinancialNormalizerRoute,
  AppInvestmentMemoRoute: AppInvestmentMemoRoute,
  AppOptimizationRoute: AppOptimizationRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskScannerRoute: AppRiskScannerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopifyConnectRoute: AppShopifyConnectRoute,
  AppValuationRoute: AppValuationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
