/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppValuationRouteImport } from './routes/_app.valuation'
import { Route as AppStoreDataRouteImport } from './routes/_app.store-data'
import { Route as AppShopifyConnectRouteImport } from './routes/_app.shopify-connect'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRiskScannerRouteImport } from './routes/_app.risk-scanner'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOptimizationRouteImport } from './routes/_app.optimization'
import { Route as AppMetaOauthCallbackRouteImport } from './routes/_app.meta-oauth-callback'
import { Route as AppMetaDataRouteImport } from './routes/_app.meta-data'
import { Route as AppMetaConnectRouteImport } from './routes/_app.meta-connect'
import { Route as AppInvestmentMemoRouteImport } from './routes/_app.investment-memo'
import { Route as AppFinancialNormalizerRouteImport } from './routes/_app.financial-normalizer'
import { Route as AppExitScoreRouteImport } from './routes/_app.exit-score'
import { Route as AppDataSourcesRouteImport } from './routes/_app.data-sources'
import { Route as AppDataRoomRouteImport } from './routes/_app.data-room'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBuyerMatchingRouteImport } from './routes/_app.buyer-matching'
import { Route as AppBillingRouteImport } from './routes/_app.billing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValuationRoute = AppValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreDataRoute = AppStoreDataRouteImport.update({
  id: '/store-data',
  path: '/store-data',
  getParentRoute: () => AppRoute,
} as any)
const AppShopifyConnectRoute = AppShopifyConnectRouteImport.update({
  id: '/shopify-connect',
  path: '/shopify-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskScannerRoute = AppRiskScannerRouteImport.update({
  id: '/risk-scanner',
  path: '/risk-scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizationRoute = AppOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => AppRoute,
} as any)
const AppMetaOauthCallbackRoute = AppMetaOauthCallbackRouteImport.update({
  id: '/meta-oauth-callback',
  path: '/meta-oauth-callback',
  getParentRoute: () => AppRoute,
} as any)
const AppMetaDataRoute = AppMetaDataRouteImport.update({
  id: '/meta-data',
  path: '/meta-data',
  getParentRoute: () => AppRoute,
} as any)
const AppMetaConnectRoute = AppMetaConnectRouteImport.update({
  id: '/meta-connect',
  path: '/meta-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentMemoRoute = AppInvestmentMemoRouteImport.update({
  id: '/investment-memo',
  path: '/investment-memo',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialNormalizerRoute = AppFinancialNormalizerRouteImport.update({
  id: '/financial-normalizer',
  path: '/financial-normalizer',
  getParentRoute: () => AppRoute,
} as any)
const AppExitScoreRoute = AppExitScoreRouteImport.update({
  id: '/exit-score',
  path: '/exit-score',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSourcesRoute = AppDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoomRoute = AppDataRoomRouteImport.update({
  id: '/data-room',
  path: '/data-room',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerMatchingRoute = AppBuyerMatchingRouteImport.update({
  id: '/buyer-matching',
  path: '/buyer-matching',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/buyer-matching': typeof AppBuyerMatchingRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-room': typeof AppDataRoomRoute
  '/data-sources': typeof AppDataSourcesRoute
  '/exit-score': typeof AppExitScoreRoute
  '/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/investment-memo': typeof AppInvestmentMemoRoute
  '/meta-connect': typeof AppMetaConnectRoute
  '/meta-data': typeof AppMetaDataRoute
  '/meta-oauth-callback': typeof AppMetaOauthCallbackRoute
  '/optimization': typeof AppOptimizationRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/risk-scanner': typeof AppRiskScannerRoute
  '/settings': typeof AppSettingsRoute
  '/shopify-connect': typeof AppShopifyConnectRoute
  '/store-data': typeof AppStoreDataRoute
  '/valuation': typeof AppValuationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/buyer-matching': typeof AppBuyerMatchingRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-room': typeof AppDataRoomRoute
  '/data-sources': typeof AppDataSourcesRoute
  '/exit-score': typeof AppExitScoreRoute
  '/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/investment-memo': typeof AppInvestmentMemoRoute
  '/meta-connect': typeof AppMetaConnectRoute
  '/meta-data': typeof AppMetaDataRoute
  '/meta-oauth-callback': typeof AppMetaOauthCallbackRoute
  '/optimization': typeof AppOptimizationRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/risk-scanner': typeof AppRiskScannerRoute
  '/settings': typeof AppSettingsRoute
  '/shopify-connect': typeof AppShopifyConnectRoute
  '/store-data': typeof AppStoreDataRoute
  '/valuation': typeof AppValuationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/buyer-matching': typeof AppBuyerMatchingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/data-room': typeof AppDataRoomRoute
  '/_app/data-sources': typeof AppDataSourcesRoute
  '/_app/exit-score': typeof AppExitScoreRoute
  '/_app/financial-normalizer': typeof AppFinancialNormalizerRoute
  '/_app/investment-memo': typeof AppInvestmentMemoRoute
  '/_app/meta-connect': typeof AppMetaConnectRoute
  '/_app/meta-data': typeof AppMetaDataRoute
  '/_app/meta-oauth-callback': typeof AppMetaOauthCallbackRoute
  '/_app/optimization': typeof AppOptimizationRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/risk-scanner': typeof AppRiskScannerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shopify-connect': typeof AppShopifyConnectRoute
  '/_app/store-data': typeof AppStoreDataRoute
  '/_app/valuation': typeof AppValuationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-deletion'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/billing'
    | '/buyer-matching'
    | '/dashboard'
    | '/data-room'
    | '/data-sources'
    | '/exit-score'
    | '/financial-normalizer'
    | '/investment-memo'
    | '/meta-connect'
    | '/meta-data'
    | '/meta-oauth-callback'
    | '/optimization'
    | '/profile'
    | '/reports'
    | '/risk-scanner'
    | '/settings'
    | '/shopify-connect'
    | '/store-data'
    | '/valuation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-deletion'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/billing'
    | '/buyer-matching'
    | '/dashboard'
    | '/data-room'
    | '/data-sources'
    | '/exit-score'
    | '/financial-normalizer'
    | '/investment-memo'
    | '/meta-connect'
    | '/meta-data'
    | '/meta-oauth-callback'
    | '/optimization'
    | '/profile'
    | '/reports'
    | '/risk-scanner'
    | '/settings'
    | '/shopify-connect'
    | '/store-data'
    | '/valuation'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/data-deletion'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/_app/billing'
    | '/_app/buyer-matching'
    | '/_app/dashboard'
    | '/_app/data-room'
    | '/_app/data-sources'
    | '/_app/exit-score'
    | '/_app/financial-normalizer'
    | '/_app/investment-memo'
    | '/_app/meta-connect'
    | '/_app/meta-data'
    | '/_app/meta-oauth-callback'
    | '/_app/optimization'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/risk-scanner'
    | '/_app/settings'
    | '/_app/shopify-connect'
    | '/_app/store-data'
    | '/_app/valuation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/valuation': {
      id: '/_app/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof AppValuationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store-data': {
      id: '/_app/store-data'
      path: '/store-data'
      fullPath: '/store-data'
      preLoaderRoute: typeof AppStoreDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopify-connect': {
      id: '/_app/shopify-connect'
      path: '/shopify-connect'
      fullPath: '/shopify-connect'
      preLoaderRoute: typeof AppShopifyConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk-scanner': {
      id: '/_app/risk-scanner'
      path: '/risk-scanner'
      fullPath: '/risk-scanner'
      preLoaderRoute: typeof AppRiskScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/optimization': {
      id: '/_app/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof AppOptimizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meta-oauth-callback': {
      id: '/_app/meta-oauth-callback'
      path: '/meta-oauth-callback'
      fullPath: '/meta-oauth-callback'
      preLoaderRoute: typeof AppMetaOauthCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meta-data': {
      id: '/_app/meta-data'
      path: '/meta-data'
      fullPath: '/meta-data'
      preLoaderRoute: typeof AppMetaDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meta-connect': {
      id: '/_app/meta-connect'
      path: '/meta-connect'
      fullPath: '/meta-connect'
      preLoaderRoute: typeof AppMetaConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investment-memo': {
      id: '/_app/investment-memo'
      path: '/investment-memo'
      fullPath: '/investment-memo'
      preLoaderRoute: typeof AppInvestmentMemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financial-normalizer': {
      id: '/_app/financial-normalizer'
      path: '/financial-normalizer'
      fullPath: '/financial-normalizer'
      preLoaderRoute: typeof AppFinancialNormalizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exit-score': {
      id: '/_app/exit-score'
      path: '/exit-score'
      fullPath: '/exit-score'
      preLoaderRoute: typeof AppExitScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-sources': {
      id: '/_app/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof AppDataSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-room': {
      id: '/_app/data-room'
      path: '/data-room'
      fullPath: '/data-room'
      preLoaderRoute: typeof AppDataRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer-matching': {
      id: '/_app/buyer-matching'
      path: '/buyer-matching'
      fullPath: '/buyer-matching'
      preLoaderRoute: typeof AppBuyerMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppBuyerMatchingRoute: typeof AppBuyerMatchingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataRoomRoute: typeof AppDataRoomRoute
  AppDataSourcesRoute: typeof AppDataSourcesRoute
  AppExitScoreRoute: typeof AppExitScoreRoute
  AppFinancialNormalizerRoute: typeof AppFinancialNormalizerRoute
  AppInvestmentMemoRoute: typeof AppInvestmentMemoRoute
  AppMetaConnectRoute: typeof AppMetaConnectRoute
  AppMetaDataRoute: typeof AppMetaDataRoute
  AppMetaOauthCallbackRoute: typeof AppMetaOauthCallbackRoute
  AppOptimizationRoute: typeof AppOptimizationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskScannerRoute: typeof AppRiskScannerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopifyConnectRoute: typeof AppShopifyConnectRoute
  AppStoreDataRoute: typeof AppStoreDataRoute
  AppValuationRoute: typeof AppValuationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppBuyerMatchingRoute: AppBuyerMatchingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataRoomRoute: AppDataRoomRoute,
  AppDataSourcesRoute: AppDataSourcesRoute,
  AppExitScoreRoute: AppExitScoreRoute,
  AppFinancialNormalizerRoute: AppFinancialNormalizerRoute,
  AppInvestmentMemoRoute: AppInvestmentMemoRoute,
  AppMetaConnectRoute: AppMetaConnectRoute,
  AppMetaDataRoute: AppMetaDataRoute,
  AppMetaOauthCallbackRoute: AppMetaOauthCallbackRoute,
  AppOptimizationRoute: AppOptimizationRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskScannerRoute: AppRiskScannerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopifyConnectRoute: AppShopifyConnectRoute,
  AppStoreDataRoute: AppStoreDataRoute,
  AppValuationRoute: AppValuationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
